import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'fa';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.vault': 'Vault',
    'nav.chat': 'AI Chat',
    'nav.profile': 'Profile',
    
    // Auth
    'auth.welcome': 'Welcome to PetCare',
    'auth.subtitle': 'Your pet\'s health companion',
    'auth.signIn': 'Sign In',
    'auth.signUp': 'Sign Up',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.fullName': 'Full Name',
    'auth.signingIn': 'Signing in...',
    'auth.creatingAccount': 'Creating account...',
    'auth.noAccount': 'Don\'t have an account?',
    'auth.hasAccount': 'Already have an account?',
    'auth.welcomeBack': 'Welcome back!',
    'auth.signInSuccess': 'You have successfully signed in.',
    'auth.invalidCredentials': 'Invalid email or password. Please try again.',
    'auth.accountCreated': 'Account created!',
    'auth.signUpSuccess': 'Welcome to PetCare! You can now sign in.',
    'auth.emailAlreadyRegistered': 'This email is already registered. Please sign in instead.',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.myPets': 'My Pets',
    'dashboard.addPet': 'Add Pet',
    'dashboard.noPets': 'No pets yet',
    'dashboard.addFirstPet': 'Add your first furry friend!',
    'dashboard.upcomingReminders': 'Upcoming Reminders',
    'dashboard.next7Days': 'Next 7 days',
    'dashboard.noReminders': 'No upcoming reminders',
    'dashboard.allReminders': 'All Reminders',
    'dashboard.allRemindersDesc': 'View all your reminders',
    'dashboard.yearsOld': 'years old',
    'dashboard.kg': 'kg',
    'dashboard.unknownBreed': 'Unknown breed',
    'dashboard.today': 'Today',
    'dashboard.tomorrow': 'Tomorrow',
    'dashboard.daysLeft': 'days',
    
    // Add Pet Dialog
    'pet.addNew': 'Add New Pet',
    'pet.edit': 'Edit Pet',
    'pet.name': 'Pet Name',
    'pet.namePlaceholder': 'e.g., Max',
    'pet.breed': 'Breed',
    'pet.breedPlaceholder': 'e.g., Golden Retriever',
    'pet.birthDate': 'Birth Date',
    'pet.weight': 'Weight (kg)',
    'pet.weightPlaceholder': 'e.g., 25',
    'pet.type': 'Pet Type',
    'pet.dog': 'Dog',
    'pet.cat': 'Cat',
    'pet.changePhoto': 'Change Photo',
    'pet.cancel': 'Cancel',
    'pet.add': 'Add Pet',
    'pet.adding': 'Adding...',
    'pet.added': 'Pet added successfully!',
    'pet.addError': 'Failed to add pet',
    'pet.updated': 'Pet updated successfully!',
    'pet.updateError': 'Failed to update pet',
    'pet.imageUploadError': 'Failed to upload image',
    
    // Add Reminder Dialog
    'reminder.addNew': 'Add Reminder',
    'reminder.title': 'Title',
    'reminder.titlePlaceholder': 'e.g., Annual vaccination',
    'reminder.type': 'Type',
    'reminder.selectType': 'Select type',
    'reminder.vaccination': 'Vaccination',
    'reminder.antiparasitic': 'Anti-parasitic',
    'reminder.checkup': 'Check-up',
    'reminder.dueDate': 'Due Date',
    'reminder.selectPet': 'Select Pet',
    'reminder.choosePet': 'Choose a pet',
    'reminder.notes': 'Notes (optional)',
    'reminder.notesPlaceholder': 'Any additional notes...',
    'reminder.cancel': 'Cancel',
    'reminder.add': 'Add Reminder',
    'reminder.adding': 'Adding...',
    'reminder.added': 'Reminder added successfully!',
    'reminder.addError': 'Failed to add reminder',
    'reminder.markComplete': 'Mark as complete',
    'reminder.completed': 'Reminder completed!',
    'reminder.reopened': 'Reminder reopened',
    'reminder.deleted': 'Reminder deleted',
    'reminder.deleteError': 'Failed to delete reminder',
    'reminder.edit': 'Edit Reminder',
    'reminder.save': 'Save Changes',
    'reminder.updated': 'Reminder updated!',
    'reminder.updateError': 'Failed to update reminder',
    'reminder.recurrence': 'Repeat',
    'reminder.every': 'Every',
    'reminder.noRepeat': 'No repeat',
    'reminder.weeks': 'Week(s)',
    'reminder.months': 'Month(s)',
    'reminder.years': 'Year(s)',
    'reminder.nextCreated': 'Next reminder created',
    'reminder.done': 'Done',
    'reminder.today': 'Today',
    'reminder.tomorrow': 'Tomorrow',
    'reminder.days': 'days',
    
    // Health Vault
    'vault.title': 'Health Vault',
    'vault.subtitle': 'Medical records & documents',
    'vault.upload': 'Upload',
    'vault.noRecords': 'No records yet',
    'vault.startUploading': 'Start uploading medical documents',
    'vault.medicalTests': 'Medical Tests',
    'vault.prescriptions': 'Prescriptions',
    'vault.passports': 'Passports & ID',
    'vault.uploadNew': 'Upload Record',
    'vault.category': 'Category',
    'vault.selectCategory': 'Select category',
    'vault.medicalTest': 'Medical Test',
    'vault.prescription': 'Prescription',
    'vault.passport': 'Passport/ID',
    'vault.recordTitle': 'Title',
    'vault.titlePlaceholder': 'e.g., Blood test results',
    'vault.recordDate': 'Record Date',
    'vault.image': 'Image',
    'vault.uploading': 'Uploading...',
    'vault.uploaded': 'Record uploaded successfully!',
    'vault.uploadError': 'Failed to upload record',
    'vault.allPets': 'All Pets',
    'vault.deleted': 'Record deleted successfully!',
    'vault.deleteError': 'Failed to delete record',
    'vault.deleteConfirmTitle': 'Delete Record',
    'vault.deleteConfirmMessage': 'Are you sure you want to delete this record? This action cannot be undone.',
    'vault.editRecord': 'Edit Record',
    'vault.updated': 'Record updated successfully!',
    'vault.updateError': 'Failed to update record',
    'vault.notes': 'Notes',
    'vault.notesPlaceholder': 'Add any notes...',
    'vault.pet': 'Pet',
    'vault.untitledRecord': 'Untitled Record',
    'vault.viewFullImage': 'View full image',
    
    // AI Chat
    'chat.title': 'AI Vet Assistant',
    'chat.subtitle': 'Ask me anything about pet health',
    'chat.selectPet': 'Select pet for context',
    'chat.allPets': 'All pets',
    'chat.placeholder': 'Ask about your pet\'s health...',
    'chat.send': 'Send',
    'chat.thinking': 'Thinking...',
    'chat.error': 'Failed to get response',
    'chat.suggestion1': 'What vaccines does my pet need?',
    'chat.suggestion2': 'Signs of common pet illnesses',
    'chat.suggestion3': 'Diet tips for my pet',
    'chat.newChat': 'New Chat',
    'chat.noChats': 'No chats yet. Start a new conversation!',
    'chat.welcome': 'Hello! 👋',
    'chat.disclaimer': 'AI advice is not a substitute for professional veterinary care.',
    'chat.history': 'Chat History',
    
    // Profile
    'profile.title': 'Profile',
    'profile.editProfile': 'Edit Profile',
    'profile.fullName': 'Full Name',
    'profile.email': 'Email',
    'profile.save': 'Save',
    'profile.saving': 'Saving...',
    'profile.saved': 'Profile updated!',
    'profile.saveError': 'Failed to update profile',
    'profile.signOut': 'Sign Out',
    'profile.signingOut': 'Signing out...',
    'profile.pets': 'Pets',
    'profile.reminders': 'Reminders',
    'profile.records': 'Records',
    'profile.language': 'Language',
    'profile.english': 'English',
    'profile.persian': 'فارسی',
    'profile.notifications': 'Notifications',
    'profile.pushNotifications': 'Push Notifications',
    'profile.pushNotificationsDesc': 'Get notified when reminders are due',
    'profile.emailNotifications': 'Email Notifications',
    'profile.emailNotificationsDesc': 'Receive daily reminder emails',
    'profile.pushPermissionDenied': 'Permission Denied',
    'profile.pushPermissionDeniedDesc': 'Please enable notifications in your browser settings',
    'profile.pushNotSupported': 'Push notifications are not supported in this browser',
    'profile.testEmail': 'Send Test Email',
    'profile.testEmailDesc': 'Send a test reminder email to check if it works',
    'profile.testEmailSent': 'Test Email Sent',
    'profile.testEmailSentDesc': 'Check your inbox for the reminder email',
    'profile.testEmailError': 'Failed to send test email',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'An error occurred',
    'common.retry': 'Retry',
    'common.save': 'Save',
    'common.saving': 'Saving...',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.all': 'All',
    'common.selectDate': 'Select date',
    
    // Vault extras
    'vault.fileTooLarge': 'File size must be less than 10MB',
    'vault.changeImage': 'Change Image',
  },
  fa: {
    // Navigation
    'nav.dashboard': 'داشبورد',
    'nav.vault': 'پرونده',
    'nav.chat': 'مشاوره',
    'nav.profile': 'پروفایل',
    
    // Auth
    'auth.welcome': 'به پت‌کر خوش آمدید',
    'auth.subtitle': 'همراه سلامت پت شما',
    'auth.signIn': 'ورود',
    'auth.signUp': 'ثبت نام',
    'auth.email': 'ایمیل',
    'auth.password': 'رمز عبور',
    'auth.fullName': 'نام کامل',
    'auth.signingIn': 'در حال ورود...',
    'auth.creatingAccount': 'در حال ساخت حساب...',
    'auth.noAccount': 'حساب کاربری ندارید؟',
    'auth.hasAccount': 'قبلاً ثبت نام کرده‌اید؟',
    'auth.welcomeBack': 'خوش آمدید!',
    'auth.signInSuccess': 'با موفقیت وارد شدید.',
    'auth.invalidCredentials': 'ایمیل یا رمز عبور اشتباه است. لطفاً دوباره تلاش کنید.',
    'auth.accountCreated': 'حساب ایجاد شد!',
    'auth.signUpSuccess': 'به پت‌پل خوش آمدید! اکنون می‌توانید وارد شوید.',
    'auth.emailAlreadyRegistered': 'این ایمیل قبلاً ثبت شده است. لطفاً وارد شوید.',
    
    // Dashboard
    'dashboard.title': 'داشبورد',
    'dashboard.myPets': 'پت‌های من',
    'dashboard.addPet': 'افزودن',
    'dashboard.noPets': 'هنوز پتی ندارید',
    'dashboard.addFirstPet': 'اولین دوست پشمالوی خود را اضافه کنید!',
    'dashboard.upcomingReminders': 'یادآوری‌های پیش رو',
    'dashboard.next7Days': '۷ روز آینده',
    'dashboard.noReminders': 'یادآوری‌ای وجود ندارد',
    'dashboard.allReminders': 'همه یادآوری‌ها',
    'dashboard.allRemindersDesc': 'مشاهده تمام یادآوری‌های شما',
    'dashboard.allCaughtUp': 'همه چیز مرتب است! 🎉',
    'dashboard.yearsOld': 'ساله',
    'dashboard.kg': 'کیلوگرم',
    'dashboard.unknownBreed': 'نژاد نامشخص',
    'dashboard.today': 'امروز',
    'dashboard.tomorrow': 'فردا',
    'dashboard.daysLeft': 'روز',
    
    // Add Pet Dialog
    'pet.addNew': 'افزودن پت جدید',
    'pet.edit': 'ویرایش پت',
    'pet.name': 'نام پت',
    'pet.namePlaceholder': 'مثلاً: مکس',
    'pet.breed': 'نژاد',
    'pet.breedPlaceholder': 'مثلاً: گلدن رتریور',
    'pet.birthDate': 'تاریخ تولد',
    'pet.weight': 'وزن (کیلوگرم)',
    'pet.weightPlaceholder': 'مثلاً: ۲۵',
    'pet.type': 'نوع پت',
    'pet.dog': 'سگ',
    'pet.cat': 'گربه',
    'pet.changePhoto': 'تغییر عکس',
    'pet.cancel': 'انصراف',
    'pet.add': 'افزودن',
    'pet.adding': 'در حال افزودن...',
    'pet.added': 'پت با موفقیت اضافه شد!',
    'pet.addError': 'خطا در افزودن پت',
    'pet.updated': 'پت با موفقیت بروزرسانی شد!',
    'pet.updateError': 'خطا در بروزرسانی پت',
    'pet.imageUploadError': 'خطا در آپلود تصویر',
    
    // Add Reminder Dialog
    'reminder.addNew': 'افزودن یادآوری',
    'reminder.title': 'عنوان',
    'reminder.titlePlaceholder': 'مثلاً: واکسیناسیون سالانه',
    'reminder.type': 'نوع',
    'reminder.selectType': 'انتخاب نوع',
    'reminder.vaccination': 'واکسیناسیون',
    'reminder.antiparasitic': 'ضد انگل',
    'reminder.checkup': 'معاینه',
    'reminder.dueDate': 'تاریخ سررسید',
    'reminder.selectPet': 'انتخاب پت',
    'reminder.choosePet': 'یک پت انتخاب کنید',
    'reminder.notes': 'یادداشت (اختیاری)',
    'reminder.notesPlaceholder': 'توضیحات اضافی...',
    'reminder.cancel': 'انصراف',
    'reminder.add': 'افزودن',
    'reminder.adding': 'در حال افزودن...',
    'reminder.added': 'یادآوری با موفقیت اضافه شد!',
    'reminder.addError': 'خطا در افزودن یادآوری',
    'reminder.markComplete': 'تکمیل شد',
    'reminder.completed': 'یادآوری تکمیل شد!',
    'reminder.reopened': 'یادآوری بازگشایی شد',
    'reminder.deleted': 'یادآوری حذف شد',
    'reminder.deleteError': 'خطا در حذف یادآوری',
    'reminder.edit': 'ویرایش یادآوری',
    'reminder.save': 'ذخیره تغییرات',
    'reminder.updated': 'یادآوری بروزرسانی شد!',
    'reminder.updateError': 'خطا در بروزرسانی یادآوری',
    'reminder.recurrence': 'تکرار',
    'reminder.every': 'هر',
    'reminder.noRepeat': 'بدون تکرار',
    'reminder.weeks': 'هفته',
    'reminder.months': 'ماه',
    'reminder.years': 'سال',
    'reminder.nextCreated': 'یادآوری بعدی ایجاد شد',
    'reminder.done': 'انجام شد',
    'reminder.today': 'امروز',
    'reminder.tomorrow': 'فردا',
    'reminder.days': 'روز',
    
    // Health Vault
    'vault.title': 'پرونده سلامت',
    'vault.subtitle': 'مدارک و اسناد پزشکی',
    'vault.upload': 'آپلود',
    'vault.noRecords': 'هنوز مدرکی وجود ندارد',
    'vault.startUploading': 'شروع به آپلود اسناد پزشکی کنید',
    'vault.medicalTests': 'آزمایشات',
    'vault.prescriptions': 'نسخه‌ها',
    'vault.passports': 'شناسنامه',
    'vault.uploadNew': 'آپلود مدرک',
    'vault.category': 'دسته‌بندی',
    'vault.selectCategory': 'انتخاب دسته‌بندی',
    'vault.medicalTest': 'آزمایش پزشکی',
    'vault.prescription': 'نسخه',
    'vault.passport': 'شناسنامه/پاسپورت',
    'vault.recordTitle': 'عنوان',
    'vault.titlePlaceholder': 'مثلاً: نتایج آزمایش خون',
    'vault.recordDate': 'تاریخ مدرک',
    'vault.image': 'تصویر',
    'vault.uploading': 'در حال آپلود...',
    'vault.uploaded': 'مدرک با موفقیت آپلود شد!',
    'vault.uploadError': 'خطا در آپلود مدرک',
    'vault.allPets': 'همه پت‌ها',
    'vault.deleted': 'مدرک با موفقیت حذف شد!',
    'vault.deleteError': 'خطا در حذف مدرک',
    'vault.deleteConfirmTitle': 'حذف مدرک',
    'vault.deleteConfirmMessage': 'آیا مطمئن هستید که می‌خواهید این مدرک را حذف کنید؟ این عمل قابل بازگشت نیست.',
    'vault.editRecord': 'ویرایش مدرک',
    'vault.updated': 'مدرک با موفقیت بروزرسانی شد!',
    'vault.updateError': 'خطا در بروزرسانی مدرک',
    'vault.notes': 'یادداشت',
    'vault.notesPlaceholder': 'یادداشت اضافه کنید...',
    'vault.pet': 'حیوان',
    'vault.untitledRecord': 'مدرک بدون عنوان',
    'vault.viewFullImage': 'مشاهده تصویر کامل',
    
    // AI Chat
    'chat.title': 'دستیار هوش مصنوعی دامپزشکی',
    'chat.subtitle': 'هر سوالی درباره سلامت پت بپرسید',
    'chat.selectPet': 'انتخاب پت برای مشاوره',
    'chat.allPets': 'همه پت‌ها',
    'chat.placeholder': 'سوال خود را درباره سلامت پت بپرسید...',
    'chat.send': 'ارسال',
    'chat.thinking': 'در حال فکر کردن...',
    'chat.error': 'خطا در دریافت پاسخ',
    'chat.suggestion1': 'پت من به چه واکسن‌هایی نیاز دارد؟',
    'chat.suggestion2': 'علائم بیماری‌های رایج پت‌ها',
    'chat.suggestion3': 'نکات تغذیه‌ای برای پت من',
    'chat.newChat': 'گفتگوی جدید',
    'chat.noChats': 'هنوز گفتگویی ندارید. یک مکالمه جدید شروع کنید!',
    'chat.welcome': 'سلام! 👋',
    'chat.disclaimer': 'مشاوره هوش مصنوعی جایگزین مراقبت‌های دامپزشکی حرفه‌ای نیست.',
    'chat.history': 'تاریخچه گفتگو',
    
    // Profile
    'profile.title': 'پروفایل',
    'profile.editProfile': 'ویرایش پروفایل',
    'profile.fullName': 'نام کامل',
    'profile.email': 'ایمیل',
    'profile.save': 'ذخیره',
    'profile.saving': 'در حال ذخیره...',
    'profile.saved': 'پروفایل بروزرسانی شد!',
    'profile.saveError': 'خطا در بروزرسانی پروفایل',
    'profile.signOut': 'خروج',
    'profile.signingOut': 'در حال خروج...',
    'profile.pets': 'پت‌ها',
    'profile.reminders': 'یادآوری‌ها',
    'profile.records': 'مدارک',
    'profile.language': 'زبان',
    'profile.english': 'English',
    'profile.persian': 'فارسی',
    'profile.notifications': 'اعلان‌ها',
    'profile.pushNotifications': 'اعلان‌های فوری',
    'profile.pushNotificationsDesc': 'هنگام سررسید یادآوری‌ها مطلع شوید',
    'profile.emailNotifications': 'اعلان‌های ایمیلی',
    'profile.emailNotificationsDesc': 'ایمیل روزانه یادآوری دریافت کنید',
    'profile.pushPermissionDenied': 'دسترسی رد شد',
    'profile.pushPermissionDeniedDesc': 'لطفاً اعلان‌ها را در تنظیمات مرورگر فعال کنید',
    'profile.pushNotSupported': 'اعلان‌های فوری در این مرورگر پشتیبانی نمی‌شود',
    'profile.testEmail': 'ارسال ایمیل آزمایشی',
    'profile.testEmailDesc': 'یک ایمیل یادآوری آزمایشی ارسال کنید',
    'profile.testEmailSent': 'ایمیل آزمایشی ارسال شد',
    'profile.testEmailSentDesc': 'صندوق ورودی خود را برای ایمیل یادآوری بررسی کنید',
    'profile.testEmailError': 'خطا در ارسال ایمیل آزمایشی',
    
    // Common
    'common.loading': 'در حال بارگذاری...',
    'common.error': 'خطایی رخ داد',
    'common.retry': 'تلاش مجدد',
    'common.save': 'ذخیره',
    'common.saving': 'در حال ذخیره...',
    'common.cancel': 'انصراف',
    'common.delete': 'حذف',
    'common.edit': 'ویرایش',
    'common.all': 'همه',
    'common.selectDate': 'انتخاب تاریخ',
    
    // Vault extras
    'vault.fileTooLarge': 'حجم فایل باید کمتر از ۱۰ مگابایت باشد',
    'vault.changeImage': 'تغییر تصویر',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('petcare-language');
    return (saved as Language) || 'fa';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('petcare-language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  const isRTL = language === 'fa';

  useEffect(() => {
    document.documentElement.dir = isRTL ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
    document.documentElement.classList.toggle('rtl', isRTL);
  }, [isRTL, language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
